### PR TITLE
add peter profile

### PR DESCRIPTION
**Pull request by thepeted**

### CODE REVIEW

**Comment by KeiranWDigital** [comment]
Please could you add an include in `people.html`

The following syntax will work `{% include_relative pages-people/people-peter.html %}`

If you'd have done a yml profile it would have been included automatically

**Review by KeiranWDigital — CHANGES_REQUESTED** [review]
Please could you add an include in people.html

The following syntax will work {% include_relative pages-people/people-peter.html %}

If you'd have done a yml profile it would have been included automatically

**Comment by KeiranWDigital** [comment]
Thanks for adding your profile btw! 🙂

**Comment by thepeted** [comment]
Thanks for the reminder to add the include :-)

**Review by KeiranWDigital — APPROVED** [review]

**Pull request merged**
